[bootstrap.user]
login_shell = "/usr/bin/fish"

[bootstrap.hooks]
post-packages = "fc-cache -f ~/.local/share/fonts"

[env]
REQUESTS_CA_BUNDLE = "/etc/ssl/certs/ca-certificates.crt"

[bootstrap.packages]
"dnf:fish" = "latest"
