[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"

[dotfiles]
"~/Library/Keyboard Layouts" = { source = "home/Library/Keyboard Layouts", mode = "symlink-each", manifest = "git" }
"~/.config/karabiner" = { source = "home/.config/karabiner", mode = "copy" }

# workaround: mise breaks the ad-hoc signature when relocating the fish bottle
# TODO: report bug in Mise
[bootstrap.hooks]
post-packages = "codesign --force --sign - /opt/homebrew/Cellar/fish/*/bin/fish"

[env]
DOCKER_HOST = "unix://{{ env.HOME }}/.config/colima/default/docker.sock"
_.path = ["/opt/homebrew/bin", "/opt/homebrew/sbin"]

[bootstrap.packages]
"brew:fish" = "latest"
"brew-cask:arc" = "latest"
"brew-cask:bettercapture" = "latest"
"brew-cask:deskpad" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:gimp" = "latest"
"brew-cask:heynote" = "latest"
"brew-cask:inkscape" = "latest"
# "brew-cask:karabiner-elements" = "latest" # TODO: report bug in Mise
"brew-cask:mac-mouse-fix" = "latest"
"brew-cask:meetingbar" = "latest"
"brew-cask:mitmproxy" = "latest"
"brew-cask:monitorcontrol" = "latest"
"brew-cask:zed" = "latest"
