[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = []

[tools]
"1password" = "latest"
"aqua:fish-shell/fish-shell" = "latest"
"bat" = "latest"
"croc" = "latest"
"claude" = "latest"
"eza" = "latest"
"fd" = "latest"
"gh" = "latest"
"github:alexpasmantier/television" = "latest"
"github:FredrikNoren/ungit" = "latest"
"github:MitMaro/git-interactive-rebase-tool" = "latest"
"gron" = "latest"
"helm" = "latest"
"hexyl" = "latest"
"htmlq" = "latest"
"jc" = "latest"
"jq" = "latest"
"kubectl" = "latest"
"ripgrep" = "latest"
"usage" = "latest"
"uv" = "latest"
"yq" = "latest"
"zoxide" = "latest"
